---
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3

# Dynamic node configuration is handled in the playbook via slurm_nodes.yml.j2 template
# This template generates a list of nodes with their private IPs for proper communication

slurm_partitions:
  - name: debug
    Nodes: "{{ groups['slurmexechosts'] | join(',') }}"
    Default: YES

# Override only what you need to change from defaults
slurm_config:
  ClusterName: cluster
  # Controller hostname - SLURM doesn't resolve this, it uses SlurmctldAddr below
  SlurmctldHost: "{{ groups['slurmservers'][0] }}"
  # Controller's private IP - this is what nodes actually connect to
  SlurmctldAddr: "{{ hostvars[groups['slurmservers'][0]].private_ip }}"
  # Enable accounting
  AccountingStorageType: accounting_storage/slurmdbd
  AccountingStorageHost: "{{ groups['slurmdbdservers'][0] }}"
  JobAcctGatherType: jobacct_gather/linux