---
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3

# Dynamic node configuration - one entry per compute host
# SLURM will autodetect CPUs, Sockets, Cores, Threads
slurm_nodes: "{{ groups['slurmexechosts'] | map('community.general.dict_kv', 'name') | list }}"

slurm_partitions:
  - name: debug
    Nodes: "{{ groups['slurmexechosts'] | join(',') }}"
    Default: YES

# Override only what you need to change from defaults
slurm_config:
  ClusterName: cluster
  SlurmctldHost: "{{ groups['slurmservers'][0] }}"
  # Enable accounting
  AccountingStorageType: accounting_storage/slurmdbd
  AccountingStorageHost: "{{ groups['slurmdbdservers'][0] }}"
  JobAcctGatherType: jobacct_gather/linux