---
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3

# Dynamic node configuration - one entry per compute host
# SLURM will autodetect CPUs, Sockets, Cores, Threads
# Use NodeAddr to specify private IP for communication
slurm_nodes:
  - name: "{{ groups['slurmexechosts'][0] }}"
    NodeAddr: "{{ hostvars[groups['slurmexechosts'][0]].private_ip }}"

slurm_partitions:
  - name: debug
    Nodes: "{{ groups['slurmexechosts'] | join(',') }}"
    Default: YES

# Override only what you need to change from defaults
slurm_config:
  ClusterName: cluster
  SlurmctldHost: "{{ groups['slurmservers'][0] }}"
  # Also set the controller's address to use private IP
  SlurmctldAddr: "{{ hostvars[groups['slurmservers'][0]].private_ip }}"
  # Enable accounting
  AccountingStorageType: accounting_storage/slurmdbd
  AccountingStorageHost: "{{ groups['slurmdbdservers'][0] }}"
  JobAcctGatherType: jobacct_gather/linux