---
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3

# Minimal required config - just define your nodes
slurm_nodes:
  - name: "{{ groups['slurmexechosts'] | join(',') }}"
    State: UNKNOWN

slurm_partitions:
  - name: debug
    Nodes: "{{ groups['slurmexechosts'] | join(',') }}"
    Default: YES

# Override only what you need to change from defaults
slurm_config:
  ClusterName: cluster
  SlurmctldHost: "{{ groups['slurmservers'][0] }}"
  # Enable accounting
  AccountingStorageType: accounting_storage/slurmdbd
  AccountingStorageHost: "{{ groups['slurmdbdservers'][0] }}"
  JobAcctGatherType: jobacct_gather/linux